<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::transaction(function () {
            DB::table('countries')->delete();

            DB::table('countries')->insert($this->countries());
			DB::unprepared('set @a = 2;');
        });
    }

    private function countries()
    {
        return [
			['id' => 1,  'uuid' => Uuid::generate(), 'name' => 'Andorra', 'code' => 'AD'],
			['id' => 2,  'uuid' => Uuid::generate(), 'name' => 'United Arab Emirates', 'code' => 'AE'],
			['id' => 3,  'uuid' => Uuid::generate(), 'name' => 'Afghanistan', 'code' => 'AF'],
			['id' => 4,  'uuid' => Uuid::generate(), 'name' => 'Antigua and Barbuda', 'code' => 'AG'],
			['id' => 5,  'uuid' => Uuid::generate(), 'name' => 'Anguilla', 'code' => 'AI'],
			['id' => 6,  'uuid' => Uuid::generate(), 'name' => 'Albania', 'code' => 'AL'],
			['id' => 7,  'uuid' => Uuid::generate(), 'name' => 'Armenia', 'code' => 'AM'],
			['id' => 8,  'uuid' => Uuid::generate(), 'name' => 'Angola', 'code' => 'AO'],
			['id' => 9,  'uuid' => Uuid::generate(), 'name' => 'Antarctica', 'code' => 'AQ'],
			['id' => 10,  'uuid' => Uuid::generate(), 'name' => 'Argentina', 'code' => 'AR'],
			['id' => 11,  'uuid' => Uuid::generate(), 'name' => 'American Samoa', 'code' => 'AS'],
			['id' => 12,  'uuid' => Uuid::generate(), 'name' => 'Austria', 'code' => 'AT'],
			['id' => 13,  'uuid' => Uuid::generate(), 'name' => 'Australia', 'code' => 'AU'],
			['id' => 14,  'uuid' => Uuid::generate(), 'name' => 'Aruba', 'code' => 'AW'],
			['id' => 15,  'uuid' => Uuid::generate(), 'name' => 'Åland Islands', 'code' => 'AX'],
			['id' => 16,  'uuid' => Uuid::generate(), 'name' => 'Azerbaijan', 'code' => 'AZ'],
			['id' => 17,  'uuid' => Uuid::generate(), 'name' => 'Bosnia and Herzegovina', 'code' => 'BA'],
			['id' => 18,  'uuid' => Uuid::generate(), 'name' => 'Barbados', 'code' => 'BB'],
			['id' => 19,  'uuid' => Uuid::generate(), 'name' => 'Bangladesh', 'code' => 'BD'],
			['id' => 20,  'uuid' => Uuid::generate(), 'name' => 'Belgium', 'code' => 'BE'],
			['id' => 21,  'uuid' => Uuid::generate(), 'name' => 'Burkina Faso', 'code' => 'BF'],
			['id' => 22,  'uuid' => Uuid::generate(), 'name' => 'Bulgaria', 'code' => 'BG'],
			['id' => 23,  'uuid' => Uuid::generate(), 'name' => 'Bahrain', 'code' => 'BH'],
			['id' => 24,  'uuid' => Uuid::generate(), 'name' => 'Burundi', 'code' => 'BI'],
			['id' => 25,  'uuid' => Uuid::generate(), 'name' => 'Benin', 'code' => 'BJ'],
			['id' => 26,  'uuid' => Uuid::generate(), 'name' => 'Saint Barthélemy', 'code' => 'BL'],
			['id' => 27,  'uuid' => Uuid::generate(), 'name' => 'Bermuda', 'code' => 'BM'],
			['id' => 28,  'uuid' => Uuid::generate(), 'name' => 'Brunei Darussalam', 'code' => 'BN'],
			['id' => 29,  'uuid' => Uuid::generate(), 'name' => 'Bolivia', 'code' => 'BO'],
			['id' => 30,  'uuid' => Uuid::generate(), 'name' => 'Caribbean Netherlands ', 'code' => 'BQ'],
			['id' => 31,  'uuid' => Uuid::generate(), 'name' => 'Brazil', 'code' => 'BR'],
			['id' => 32,  'uuid' => Uuid::generate(), 'name' => 'Bahamas', 'code' => 'BS'],
			['id' => 33,  'uuid' => Uuid::generate(), 'name' => 'Bhutan', 'code' => 'BT'],
			['id' => 34,  'uuid' => Uuid::generate(), 'name' => 'Bouvet Island', 'code' => 'BV'],
			['id' => 35,  'uuid' => Uuid::generate(), 'name' => 'Botswana', 'code' => 'BW'],
			['id' => 36,  'uuid' => Uuid::generate(), 'name' => 'Belarus', 'code' => 'BY'],
			['id' => 37,  'uuid' => Uuid::generate(), 'name' => 'Belize', 'code' => 'BZ'],
			['id' => 38,  'uuid' => Uuid::generate(), 'name' => 'Canada', 'code' => 'CA'],
			['id' => 39,  'uuid' => Uuid::generate(), 'name' => 'Cocos (Keeling) Islands', 'code' => 'CC'],
			['id' => 40,  'uuid' => Uuid::generate(), 'name' => 'Congo, Democratic Republic of', 'code' => 'CD'],
			['id' => 41,  'uuid' => Uuid::generate(), 'name' => 'Central African Republic', 'code' => 'CF'],
			['id' => 42,  'uuid' => Uuid::generate(), 'name' => 'Congo', 'code' => 'CG'],
			['id' => 43,  'uuid' => Uuid::generate(), 'name' => 'Switzerland', 'code' => 'CH'],
			['id' => 44,  'uuid' => Uuid::generate(), 'name' => 'Côte d\'Ivoire', 'code' => 'CI'],
			['id' => 45,  'uuid' => Uuid::generate(), 'name' => 'Cook Islands', 'code' => 'CK'],
			['id' => 46,  'uuid' => Uuid::generate(), 'name' => 'Chile', 'code' => 'CL'],
			['id' => 47,  'uuid' => Uuid::generate(), 'name' => 'Cameroon', 'code' => 'CM'],
			['id' => 48,  'uuid' => Uuid::generate(), 'name' => 'China', 'code' => 'CN'],
			['id' => 49,  'uuid' => Uuid::generate(), 'name' => 'Colombia', 'code' => 'CO'],
			['id' => 50,  'uuid' => Uuid::generate(), 'name' => 'Costa Rica', 'code' => 'CR'],
			['id' => 51,  'uuid' => Uuid::generate(), 'name' => 'Cuba', 'code' => 'CU'],
			['id' => 52,  'uuid' => Uuid::generate(), 'name' => 'Cape Verde', 'code' => 'CV'],
			['id' => 53,  'uuid' => Uuid::generate(), 'name' => 'Curaçao', 'code' => 'CW'],
			['id' => 54,  'uuid' => Uuid::generate(), 'name' => 'Christmas Island', 'code' => 'CX'],
			['id' => 55,  'uuid' => Uuid::generate(), 'name' => 'Cyprus', 'code' => 'CY'],
			['id' => 56,  'uuid' => Uuid::generate(), 'name' => 'Czech Republic', 'code' => 'CZ'],
			['id' => 57,  'uuid' => Uuid::generate(), 'name' => 'Germany', 'code' => 'DE'],
			['id' => 58,  'uuid' => Uuid::generate(), 'name' => 'Djibouti', 'code' => 'DJ'],
			['id' => 59,  'uuid' => Uuid::generate(), 'name' => 'Denmark', 'code' => 'DK'],
			['id' => 60,  'uuid' => Uuid::generate(), 'name' => 'Dominica', 'code' => 'DM'],
			['id' => 61,  'uuid' => Uuid::generate(), 'name' => 'Dominican Republic', 'code' => 'DO'],
			['id' => 62,  'uuid' => Uuid::generate(), 'name' => 'Algeria', 'code' => 'DZ'],
			['id' => 63,  'uuid' => Uuid::generate(), 'name' => 'Ecuador', 'code' => 'EC'],
			['id' => 64,  'uuid' => Uuid::generate(), 'name' => 'Estonia', 'code' => 'EE'],
			['id' => 65,  'uuid' => Uuid::generate(), 'name' => 'Egypt', 'code' => 'EG'],
			['id' => 66,  'uuid' => Uuid::generate(), 'name' => 'Western Sahara', 'code' => 'EH'],
			['id' => 67,  'uuid' => Uuid::generate(), 'name' => 'Eritrea', 'code' => 'ER'],
			['id' => 68,  'uuid' => Uuid::generate(), 'name' => 'Spain', 'code' => 'ES'],
			['id' => 69,  'uuid' => Uuid::generate(), 'name' => 'Ethiopia', 'code' => 'ET'],
			['id' => 70,  'uuid' => Uuid::generate(), 'name' => 'Finland', 'code' => 'FI'],
			['id' => 71,  'uuid' => Uuid::generate(), 'name' => 'Fiji', 'code' => 'FJ'],
			['id' => 72,  'uuid' => Uuid::generate(), 'name' => 'Falkland Islands', 'code' => 'FK'],
			['id' => 73,  'uuid' => Uuid::generate(), 'name' => 'Micronesia, Federated States of', 'code' => 'FM'],
			['id' => 74,  'uuid' => Uuid::generate(), 'name' => 'Faroe Islands', 'code' => 'FO'],
			['id' => 75,  'uuid' => Uuid::generate(), 'name' => 'France', 'code' => 'FR'],
			['id' => 76,  'uuid' => Uuid::generate(), 'name' => 'Gabon', 'code' => 'GA'],
			['id' => 77,  'uuid' => Uuid::generate(), 'name' => 'United Kingdom', 'code' => 'GB'],
			['id' => 78,  'uuid' => Uuid::generate(), 'name' => 'Grenada', 'code' => 'GD'],
			['id' => 79,  'uuid' => Uuid::generate(), 'name' => 'Georgia', 'code' => 'GE'],
			['id' => 80,  'uuid' => Uuid::generate(), 'name' => 'French Guiana', 'code' => 'GF'],
			['id' => 81,  'uuid' => Uuid::generate(), 'name' => 'Guernsey', 'code' => 'GG'],
			['id' => 82,  'uuid' => Uuid::generate(), 'name' => 'Ghana', 'code' => 'GH'],
			['id' => 83,  'uuid' => Uuid::generate(), 'name' => 'Gibraltar', 'code' => 'GI'],
			['id' => 84,  'uuid' => Uuid::generate(), 'name' => 'Greenland', 'code' => 'GL'],
			['id' => 85,  'uuid' => Uuid::generate(), 'name' => 'Gambia', 'code' => 'GM'],
			['id' => 86,  'uuid' => Uuid::generate(), 'name' => 'Guinea', 'code' => 'GN'],
			['id' => 87,  'uuid' => Uuid::generate(), 'name' => 'Guadeloupe', 'code' => 'GP'],
			['id' => 88,  'uuid' => Uuid::generate(), 'name' => 'Equatorial Guinea', 'code' => 'GQ'],
			['id' => 89,  'uuid' => Uuid::generate(), 'name' => 'Greece', 'code' => 'GR'],
			['id' => 90,  'uuid' => Uuid::generate(), 'name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
			['id' => 91,  'uuid' => Uuid::generate(), 'name' => 'Guatemala', 'code' => 'GT'],
			['id' => 92,  'uuid' => Uuid::generate(), 'name' => 'Guam', 'code' => 'GU'],
			['id' => 93,  'uuid' => Uuid::generate(), 'name' => 'Guinea-Bissau', 'code' => 'GW'],
			['id' => 94,  'uuid' => Uuid::generate(), 'name' => 'Guyana', 'code' => 'GY'],
			['id' => 95,  'uuid' => Uuid::generate(), 'name' => 'Hong Kong', 'code' => 'HK'],
			['id' => 96,  'uuid' => Uuid::generate(), 'name' => 'Heard and McDonald Islands', 'code' => 'HM'],
			['id' => 97,  'uuid' => Uuid::generate(), 'name' => 'Honduras', 'code' => 'HN'],
			['id' => 98,  'uuid' => Uuid::generate(), 'name' => 'Croatia', 'code' => 'HR'],
			['id' => 99,  'uuid' => Uuid::generate(), 'name' => 'Haiti', 'code' => 'HT'],
			['id' => 100,  'uuid' => Uuid::generate(), 'name' => 'Hungary', 'code' => 'HU'],
			['id' => 101,  'uuid' => Uuid::generate(), 'name' => 'Indonesia', 'code' => 'ID'],
			['id' => 102,  'uuid' => Uuid::generate(), 'name' => 'Ireland', 'code' => 'IE'],
			['id' => 103,  'uuid' => Uuid::generate(), 'name' => 'Israel', 'code' => 'IL'],
			['id' => 104,  'uuid' => Uuid::generate(), 'name' => 'Isle of Man', 'code' => 'IM'],
			['id' => 105,  'uuid' => Uuid::generate(), 'name' => 'India', 'code' => 'IN'],
			['id' => 106,  'uuid' => Uuid::generate(), 'name' => 'British Indian Ocean Territory', 'code' => 'IO'],
			['id' => 107,  'uuid' => Uuid::generate(), 'name' => 'Iraq', 'code' => 'IQ'],
			['id' => 108,  'uuid' => Uuid::generate(), 'name' => 'Iran', 'code' => 'IR'],
			['id' => 109,  'uuid' => Uuid::generate(), 'name' => 'Iceland', 'code' => 'IS'],
			['id' => 110,  'uuid' => Uuid::generate(), 'name' => 'Italy', 'code' => 'IT'],
			['id' => 111,  'uuid' => Uuid::generate(), 'name' => 'Jersey', 'code' => 'JE'],
			['id' => 112,  'uuid' => Uuid::generate(), 'name' => 'Jamaica', 'code' => 'JM'],
			['id' => 113,  'uuid' => Uuid::generate(), 'name' => 'Jordan', 'code' => 'JO'],
			['id' => 114,  'uuid' => Uuid::generate(), 'name' => 'Japan', 'code' => 'JP'],
			['id' => 115,  'uuid' => Uuid::generate(), 'name' => 'Kenya', 'code' => 'KE'],
			['id' => 116,  'uuid' => Uuid::generate(), 'name' => 'Kyrgyzstan', 'code' => 'KG'],
			['id' => 117,  'uuid' => Uuid::generate(), 'name' => 'Cambodia', 'code' => 'KH'],
			['id' => 118,  'uuid' => Uuid::generate(), 'name' => 'Kiribati', 'code' => 'KI'],
			['id' => 119,  'uuid' => Uuid::generate(), 'name' => 'Comoros', 'code' => 'KM'],
			['id' => 120,  'uuid' => Uuid::generate(), 'name' => 'Saint Kitts and Nevis', 'code' => 'KN'],
			['id' => 121,  'uuid' => Uuid::generate(), 'name' => 'North Korea', 'code' => 'KP'],
			['id' => 122,  'uuid' => Uuid::generate(), 'name' => 'South Korea', 'code' => 'KR'],
			['id' => 123,  'uuid' => Uuid::generate(), 'name' => 'Kuwait', 'code' => 'KW'],
			['id' => 124,  'uuid' => Uuid::generate(), 'name' => 'Cayman Islands', 'code' => 'KY'],
			['id' => 125,  'uuid' => Uuid::generate(), 'name' => 'Kazakhstan', 'code' => 'KZ'],
			['id' => 126,  'uuid' => Uuid::generate(), 'name' => 'Lao People\'s Democratic Republic', 'code' => 'LA'],
			['id' => 127,  'uuid' => Uuid::generate(), 'name' => 'Lebanon', 'code' => 'LB'],
			['id' => 128,  'uuid' => Uuid::generate(), 'name' => 'Saint Lucia', 'code' => 'LC'],
			['id' => 129,  'uuid' => Uuid::generate(), 'name' => 'Liechtenstein', 'code' => 'LI'],
			['id' => 130,  'uuid' => Uuid::generate(), 'name' => 'Sri Lanka', 'code' => 'LK'],
			['id' => 131,  'uuid' => Uuid::generate(), 'name' => 'Liberia', 'code' => 'LR'],
			['id' => 132,  'uuid' => Uuid::generate(), 'name' => 'Lesotho', 'code' => 'LS'],
			['id' => 133,  'uuid' => Uuid::generate(), 'name' => 'Lithuania', 'code' => 'LT'],
			['id' => 134,  'uuid' => Uuid::generate(), 'name' => 'Luxembourg', 'code' => 'LU'],
			['id' => 135,  'uuid' => Uuid::generate(), 'name' => 'Latvia', 'code' => 'LV'],
			['id' => 136,  'uuid' => Uuid::generate(), 'name' => 'Libya', 'code' => 'LY'],
			['id' => 137,  'uuid' => Uuid::generate(), 'name' => 'Morocco', 'code' => 'MA'],
			['id' => 138,  'uuid' => Uuid::generate(), 'name' => 'Monaco', 'code' => 'MC'],
			['id' => 139,  'uuid' => Uuid::generate(), 'name' => 'Moldova', 'code' => 'MD'],
			['id' => 140,  'uuid' => Uuid::generate(), 'name' => 'Montenegro', 'code' => 'ME'],
			['id' => 141,  'uuid' => Uuid::generate(), 'name' => 'Saint-Martin (France)', 'code' => 'MF'],
			['id' => 142,  'uuid' => Uuid::generate(), 'name' => 'Madagascar', 'code' => 'MG'],
			['id' => 143,  'uuid' => Uuid::generate(), 'name' => 'Marshall Islands', 'code' => 'MH'],
			['id' => 144,  'uuid' => Uuid::generate(), 'name' => 'Macedonia', 'code' => 'MK'],
			['id' => 145,  'uuid' => Uuid::generate(), 'name' => 'Mali', 'code' => 'ML'],
			['id' => 146,  'uuid' => Uuid::generate(), 'name' => 'Myanmar', 'code' => 'MM'],
			['id' => 147,  'uuid' => Uuid::generate(), 'name' => 'Mongolia', 'code' => 'MN'],
			['id' => 148,  'uuid' => Uuid::generate(), 'name' => 'Macau', 'code' => 'MO'],
			['id' => 149,  'uuid' => Uuid::generate(), 'name' => 'Northern Mariana Islands', 'code' => 'MP'],
			['id' => 150,  'uuid' => Uuid::generate(), 'name' => 'Martinique', 'code' => 'MQ'],
			['id' => 151,  'uuid' => Uuid::generate(), 'name' => 'Mauritania', 'code' => 'MR'],
			['id' => 152,  'uuid' => Uuid::generate(), 'name' => 'Montserrat', 'code' => 'MS'],
			['id' => 153,  'uuid' => Uuid::generate(), 'name' => 'Malta', 'code' => 'MT'],
			['id' => 154,  'uuid' => Uuid::generate(), 'name' => 'Mauritius', 'code' => 'MU'],
			['id' => 155,  'uuid' => Uuid::generate(), 'name' => 'Maldives', 'code' => 'MV'],
			['id' => 156,  'uuid' => Uuid::generate(), 'name' => 'Malawi', 'code' => 'MW'],
			['id' => 157,  'uuid' => Uuid::generate(), 'name' => 'Mexico', 'code' => 'MX'],
			['id' => 158,  'uuid' => Uuid::generate(), 'name' => 'Malaysia', 'code' => 'MY'],
			['id' => 159,  'uuid' => Uuid::generate(), 'name' => 'Mozambique', 'code' => 'MZ'],
			['id' => 160,  'uuid' => Uuid::generate(), 'name' => 'Namibia', 'code' => 'NA'],
			['id' => 161,  'uuid' => Uuid::generate(), 'name' => 'New Caledonia', 'code' => 'NC'],
			['id' => 162,  'uuid' => Uuid::generate(), 'name' => 'Niger', 'code' => 'NE'],
			['id' => 163,  'uuid' => Uuid::generate(), 'name' => 'Norfolk Island', 'code' => 'NF'],
			['id' => 164,  'uuid' => Uuid::generate(), 'name' => 'Nigeria', 'code' => 'NG'],
			['id' => 165,  'uuid' => Uuid::generate(), 'name' => 'Nicaragua', 'code' => 'NI'],
			['id' => 166,  'uuid' => Uuid::generate(), 'name' => 'The Netherlands', 'code' => 'NL'],
			['id' => 167,  'uuid' => Uuid::generate(), 'name' => 'Norway', 'code' => 'NO'],
			['id' => 168,  'uuid' => Uuid::generate(), 'name' => 'Nepal', 'code' => 'NP'],
			['id' => 169,  'uuid' => Uuid::generate(), 'name' => 'Nauru', 'code' => 'NR'],
			['id' => 170,  'uuid' => Uuid::generate(), 'name' => 'Niue', 'code' => 'NU'],
			['id' => 171,  'uuid' => Uuid::generate(), 'name' => 'New Zealand', 'code' => 'NZ'],
			['id' => 172,  'uuid' => Uuid::generate(), 'name' => 'Oman', 'code' => 'OM'],
			['id' => 173,  'uuid' => Uuid::generate(), 'name' => 'Panama', 'code' => 'PA'],
			['id' => 174,  'uuid' => Uuid::generate(), 'name' => 'Peru', 'code' => 'PE'],
			['id' => 175,  'uuid' => Uuid::generate(), 'name' => 'French Polynesia', 'code' => 'PF'],
			['id' => 176,  'uuid' => Uuid::generate(), 'name' => 'Papua New Guinea', 'code' => 'PG'],
			['id' => 177,  'uuid' => Uuid::generate(), 'name' => 'Philippines', 'code' => 'PH'],
			['id' => 178,  'uuid' => Uuid::generate(), 'name' => 'Pakistan', 'code' => 'PK'],
			['id' => 179,  'uuid' => Uuid::generate(), 'name' => 'Poland', 'code' => 'PL'],
			['id' => 180,  'uuid' => Uuid::generate(), 'name' => 'St. Pierre and Miquelon', 'code' => 'PM'],
			['id' => 181,  'uuid' => Uuid::generate(), 'name' => 'Pitcairn', 'code' => 'PN'],
			['id' => 182,  'uuid' => Uuid::generate(), 'name' => 'Puerto Rico', 'code' => 'PR'],
			['id' => 183,  'uuid' => Uuid::generate(), 'name' => 'Palestine, State of', 'code' => 'PS'],
			['id' => 184,  'uuid' => Uuid::generate(), 'name' => 'Portugal', 'code' => 'PT'],
			['id' => 185,  'uuid' => Uuid::generate(), 'name' => 'Palau', 'code' => 'PW'],
			['id' => 186,  'uuid' => Uuid::generate(), 'name' => 'Paraguay', 'code' => 'PY'],
			['id' => 187,  'uuid' => Uuid::generate(), 'name' => 'Qatar', 'code' => 'QA'],
			['id' => 188,  'uuid' => Uuid::generate(), 'name' => 'Réunion', 'code' => 'RE'],
			['id' => 189,  'uuid' => Uuid::generate(), 'name' => 'Romania', 'code' => 'RO'],
			['id' => 190,  'uuid' => Uuid::generate(), 'name' => 'Serbia', 'code' => 'RS'],
			['id' => 191,  'uuid' => Uuid::generate(), 'name' => 'Russian Federation', 'code' => 'RU'],
			['id' => 192,  'uuid' => Uuid::generate(), 'name' => 'Rwanda', 'code' => 'RW'],
			['id' => 193,  'uuid' => Uuid::generate(), 'name' => 'Saudi Arabia', 'code' => 'SA'],
			['id' => 194,  'uuid' => Uuid::generate(), 'name' => 'Solomon Islands', 'code' => 'SB'],
			['id' => 195,  'uuid' => Uuid::generate(), 'name' => 'Seychelles', 'code' => 'SC'],
			['id' => 196,  'uuid' => Uuid::generate(), 'name' => 'Sudan', 'code' => 'SD'],
			['id' => 197,  'uuid' => Uuid::generate(), 'name' => 'Sweden', 'code' => 'SE'],
			['id' => 198,  'uuid' => Uuid::generate(), 'name' => 'Singapore', 'code' => 'SG'],
			['id' => 199,  'uuid' => Uuid::generate(), 'name' => 'Saint Helena', 'code' => 'SH'],
			['id' => 200,  'uuid' => Uuid::generate(), 'name' => 'Slovenia', 'code' => 'SI'],
			['id' => 201,  'uuid' => Uuid::generate(), 'name' => 'Svalbard and Jan Mayen Islands', 'code' => 'SJ'],
			['id' => 202,  'uuid' => Uuid::generate(), 'name' => 'Slovakia', 'code' => 'SK'],
			['id' => 203,  'uuid' => Uuid::generate(), 'name' => 'Sierra Leone', 'code' => 'SL'],
			['id' => 204,  'uuid' => Uuid::generate(), 'name' => 'San Marino', 'code' => 'SM'],
			['id' => 205,  'uuid' => Uuid::generate(), 'name' => 'Senegal', 'code' => 'SN'],
			['id' => 206,  'uuid' => Uuid::generate(), 'name' => 'Somalia', 'code' => 'SO'],
			['id' => 207,  'uuid' => Uuid::generate(), 'name' => 'Suriname', 'code' => 'SR'],
			['id' => 208,  'uuid' => Uuid::generate(), 'name' => 'South Sudan', 'code' => 'SS'],
			['id' => 209,  'uuid' => Uuid::generate(), 'name' => 'Sao Tome and Principe', 'code' => 'ST'],
			['id' => 210,  'uuid' => Uuid::generate(), 'name' => 'El Salvador', 'code' => 'SV'],
			['id' => 211,  'uuid' => Uuid::generate(), 'name' => 'Sint Maarten (Dutch part)', 'code' => 'SX'],
			['id' => 212,  'uuid' => Uuid::generate(), 'name' => 'Syria', 'code' => 'SY'],
			['id' => 213,  'uuid' => Uuid::generate(), 'name' => 'Swaziland', 'code' => 'SZ'],
			['id' => 214,  'uuid' => Uuid::generate(), 'name' => 'Turks and Caicos Islands', 'code' => 'TC'],
			['id' => 215,  'uuid' => Uuid::generate(), 'name' => 'Chad', 'code' => 'TD'],
			['id' => 216,  'uuid' => Uuid::generate(), 'name' => 'French Southern Territories', 'code' => 'TF'],
			['id' => 217,  'uuid' => Uuid::generate(), 'name' => 'Togo', 'code' => 'TG'],
			['id' => 218,  'uuid' => Uuid::generate(), 'name' => 'Thailand', 'code' => 'TH'],
			['id' => 219,  'uuid' => Uuid::generate(), 'name' => 'Tajikistan', 'code' => 'TJ'],
			['id' => 220,  'uuid' => Uuid::generate(), 'name' => 'Tokelau', 'code' => 'TK'],
			['id' => 221,  'uuid' => Uuid::generate(), 'name' => 'Timor-Leste', 'code' => 'TL'],
			['id' => 222,  'uuid' => Uuid::generate(), 'name' => 'Turkmenistan', 'code' => 'TM'],
			['id' => 223,  'uuid' => Uuid::generate(), 'name' => 'Tunisia', 'code' => 'TN'],
			['id' => 224,  'uuid' => Uuid::generate(), 'name' => 'Tonga', 'code' => 'TO'],
			['id' => 225,  'uuid' => Uuid::generate(), 'name' => 'Turkey', 'code' => 'TR'],
			['id' => 226,  'uuid' => Uuid::generate(), 'name' => 'Trinidad and Tobago', 'code' => 'TT'],
			['id' => 227,  'uuid' => Uuid::generate(), 'name' => 'Tuvalu', 'code' => 'TV'],
			['id' => 228,  'uuid' => Uuid::generate(), 'name' => 'Taiwan', 'code' => 'TW'],
			['id' => 229,  'uuid' => Uuid::generate(), 'name' => 'Tanzania', 'code' => 'TZ'],
			['id' => 230,  'uuid' => Uuid::generate(), 'name' => 'Ukraine', 'code' => 'UA'],
			['id' => 231,  'uuid' => Uuid::generate(), 'name' => 'Uganda', 'code' => 'UG'],
			['id' => 232,  'uuid' => Uuid::generate(), 'name' => 'United States Minor Outlying Islands', 'code' => 'UM'],
			['id' => 233,  'uuid' => Uuid::generate(), 'name' => 'United States', 'code' => 'US'],
			['id' => 234,  'uuid' => Uuid::generate(), 'name' => 'Uruguay', 'code' => 'UY'],
			['id' => 235,  'uuid' => Uuid::generate(), 'name' => 'Uzbekistan', 'code' => 'UZ'],
			['id' => 236,  'uuid' => Uuid::generate(), 'name' => 'Vatican', 'code' => 'VA'],
			['id' => 237,  'uuid' => Uuid::generate(), 'name' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
			['id' => 238,  'uuid' => Uuid::generate(), 'name' => 'Venezuela', 'code' => 'VE'],
			['id' => 239,  'uuid' => Uuid::generate(), 'name' => 'Virgin Islands (British)', 'code' => 'VG'],
			['id' => 240,  'uuid' => Uuid::generate(), 'name' => 'Virgin Islands (U.S.)', 'code' => 'VI'],
			['id' => 241,  'uuid' => Uuid::generate(), 'name' => 'Vietnam', 'code' => 'VN'],
			['id' => 242,  'uuid' => Uuid::generate(), 'name' => 'Vanuatu', 'code' => 'VU'],
			['id' => 243,  'uuid' => Uuid::generate(), 'name' => 'Wallis and Futuna Islands', 'code' => 'WF'],
			['id' => 244,  'uuid' => Uuid::generate(), 'name' => 'Samoa', 'code' => 'WS'],
			['id' => 245,  'uuid' => Uuid::generate(), 'name' => 'Yemen', 'code' => 'YE'],
			['id' => 246,  'uuid' => Uuid::generate(), 'name' => 'Mayotte', 'code' => 'YT'],
			['id' => 247,  'uuid' => Uuid::generate(), 'name' => 'South Africa', 'code' => 'ZA'],
			['id' => 248,  'uuid' => Uuid::generate(), 'name' => 'Zambia', 'code' => 'ZM'],
			['id' => 249,  'uuid' => Uuid::generate(), 'name' => 'Zimbabwe', 'code' => 'ZW'],
		];
    }
}
